export declare enum SpaceGobbling {
    NONE = "none",
    BC = "bc",
    LINES = "lines",
    STRUCTURED = "structured"
}
export declare const RuntimeConstants: {
    readonly RUNTIME_LOG_INSTANCE: "runtime.log.instance";
    readonly RUNTIME_LOG_NAME: "runtime.log.name";
    readonly RUNTIME_LOG_REFERENCE_LOG_INVALID: "runtime.log.log_invalid_references";
    readonly RUNTIME_LOG_METHOD_CALL_LOG_INVALID: "runtime.log.log_invalid_method_calls";
    readonly RUNTIME_LOG_TRACK_LOCATION: "runtime.log.track_location";
    readonly MAX_NUMBER_LOOPS: "directive.foreach.max_loops";
    readonly SKIP_INVALID_ITERATOR: "directive.foreach.skip_invalid";
    readonly CHECK_EMPTY_OBJECTS: "directive.if.empty_check";
    readonly PARSE_DIRECTIVE_MAXDEPTH: "directive.parse.max_depth";
    readonly DEFINE_DIRECTIVE_MAXDEPTH: "directive.define.max_depth";
    readonly CONTEXT_SCOPE_CONTROL: "context.scope_control";
    readonly CUSTOM_DIRECTIVES: "runtime.custom_directives";
    readonly RESOURCE_MANAGER_INSTANCE: "resource.manager.instance";
    readonly RESOURCE_MANAGER_CLASS: "resource.manager.class";
    readonly RESOURCE_MANAGER_CACHE_CLASS: "resource.manager.cache.class";
    readonly RESOURCE_MANAGER_DEFAULTCACHE_SIZE: "resource.manager.cache.default_size";
    readonly RESOURCE_MANAGER_LOGWHENFOUND: "resource.manager.log_when_found";
    readonly RESOURCE_LOADERS: "resource.loaders";
    readonly RESOURCE_LOADER: "resource.loader";
    readonly FILE_RESOURCE_LOADER_PATH: "resource.loader.file.path";
    readonly FILE_RESOURCE_LOADER_CACHE: "resource.loader.file.cache";
    readonly RESOURCE_LOADER_CLASS: "class";
    readonly RESOURCE_LOADER_INSTANCE: "instance";
    readonly RESOURCE_LOADER_CACHE: "cache";
    readonly RESOURCE_LOADER_PATHS: "path";
    readonly RESOURCE_LOADER_CHECK_INTERVAL: "modification_check_interval";
    readonly INPUT_ENCODING: "resource.default_encoding";
    readonly ENCODING_DEFAULT: "UTF-8";
    readonly EVENTHANDLER_REFERENCEINSERTION: "event_handler.reference_insertion.class";
    readonly EVENTHANDLER_METHODEXCEPTION: "event_handler.method_exception.class";
    readonly EVENTHANDLER_INCLUDE: "event_handler.include.class";
    readonly EVENTHANDLER_INVALIDREFERENCES: "event_handler.invalid_references.class";
    readonly EVENTHANDLER_INVALIDREFERENCES_QUIET: "event_handler.invalid_references.quiet";
    readonly EVENTHANDLER_INVALIDREFERENCES_NULL: "event_handler.invalid_references.null";
    readonly EVENTHANDLER_INVALIDREFERENCES_TESTED: "event_handler.invalid_references.tested";
    readonly VM_LIBRARY: "velocimacro.library.path";
    readonly VM_LIBRARY_DEFAULT: "velocimacros.vtl";
    readonly VM_LIBRARY_AUTORELOAD: "velocimacro.library.autoreload";
    readonly VM_PERM_ALLOW_INLINE: "velocimacro.inline.allow";
    readonly VM_PERM_ALLOW_INLINE_REPLACE_GLOBAL: "velocimacro.inline.replace_global";
    readonly VM_PERM_INLINE_LOCAL: "velocimacro.inline.local_scope";
    readonly VM_ARGUMENTS_STRICT: "velocimacro.arguments.strict";
    readonly VM_ENABLE_BC_MODE: "velocimacro.enable_bc_mode";
    readonly VM_MAX_DEPTH: "velocimacro.max_depth";
    readonly VM_BODY_REFERENCE: "velocimacro.body_reference";
    readonly RUNTIME_REFERENCES_STRICT: "runtime.strict_mode.enable";
    readonly RUNTIME_REFERENCES_STRICT_ESCAPE: "runtime.strict_mode.escape";
    readonly UBERSPECT_CLASSNAME: "introspector.uberspect.class";
    readonly INTROSPECTOR_RESTRICT_PACKAGES: "introspector.restrict.packages";
    readonly INTROSPECTOR_RESTRICT_CLASSES: "introspector.restrict.classes";
    readonly CONVERSION_HANDLER_CLASS: "introspector.conversion_handler.class";
    readonly CONVERSION_HANDLER_INSTANCE: "introspector.conversion_handler.instance";
    readonly PARSER_CLASS: "parser.class";
    readonly DEFAULT_PARSER_CLASS: "org.apache.velocity.runtime.parser.StandardParser";
    readonly PARSER_POOL_CLASS: "parser.pool.class";
    readonly PARSER_POOL_SIZE: "parser.pool.size";
    readonly PARSER_HYPHEN_ALLOWED: "parser.allow_hyphen_in_identifiers";
    readonly RUNTIME_STRING_INTERNING: "runtime.string_interning";
    readonly INTERPOLATE_STRINGLITERALS: "runtime.interpolate_string_literals";
    readonly IMMUTABLE_RANGES: "runtime.immutable_ranges";
    readonly STRICT_MATH: "runtime.strict_math";
    readonly CONTEXT_AUTOREFERENCE_KEY: "context.self_reference_key";
    readonly SPACE_GOBBLING: "parser.space_gobbling";
    readonly DEFAULT_RUNTIME_PROPERTIES: "org/apache/velocity/runtime/defaults/velocity.properties";
    readonly DEFAULT_RUNTIME_DIRECTIVES: "org/apache/velocity/runtime/defaults/directive.properties";
    readonly DEFAULT_RUNTIME_LOG_NAME: "org.apache.velocity";
    readonly RESOURCE_LOADER_IDENTIFIER: "_RESOURCE_LOADER_IDENTIFIER_";
    readonly NUMBER_OF_PARSERS: 20;
};
export type RuntimeProperty = typeof RuntimeConstants[keyof typeof RuntimeConstants];
